export const allIngredients = [
  "Mozzarella",
  "Basil",
  "Pepperoni",
  "Gorgonzola",
  "Parmesan",
  "Ricotta",
  "Mushrooms",
  "Olives",
  "Onions",
  "Feta cheese",
  "Red onions",
  "Sun-dried tomatoes",
  "Arugula",
  "Grilled chicken",
  "Spinach",
  "Spicy sausage",
  "Jalapeños",
  "Red chili flakes",
  "Wild mushrooms",
  "Caramelized onions",
  "Truffle oil",
  "Parsley",
  "Pineapple",
  "Ham",
  "Bacon",
  "Zucchini",
  "Bell peppers",
  "Cherry tomatoes",
  "Vegan cheese",
  "Pulled pork",
  "Red onions",
  "Corn",
  "Cheddar",
];
