import { Pizza } from "@/types/pizza.type";

export const initialPizzas: Pizza[] = [
  {
    id: 1,
    name: "Margherita",
    base: "tomato",
    ingredients: ["Mozzarella", "Basil"],
    price: 10,
    image: "/images/margherite.jpeg",
  },
  {
    id: 2,
    name: "Pepperoni",
    base: "tomato",
    ingredients: ["Mozzarella", "Pepperoni"],
    price: 12,
    image: "/images/pepperoni.jpg",
  },
  {
    id: 3,
    name: "Quattro Formaggi",
    base: "cream",
    ingredients: ["Mozzarella", "Gorgonzola", "Parmesan", "Ricotta"],
    price: 15,
    image: "/images/quattro-formaggi.jpg",
  },
  {
    id: 4,
    name: "Mediterranean Delight",
    base: "tomato",
    ingredients: [
      "Ilives",
      "Feta cheese",
      "Red onions",
      "Sun-dried tomatoes",
      "Arugula",
    ],
    price: 12,
    image: "/images/mediteranean.jpeg",
  },
  {
    id: 5,
    name: "Creamy Chicken Dream",
    base: "cream",
    ingredients: ["Grilled chicken", "Mushrooms", "Spinach", "Parmesan"],
    price: 14,
    image: "/images/creamy-chicken.jpg",
  },
  {
    id: 6,
    name: "Spicy Inferno",
    base: "tomato",
    ingredients: [
      "Spicy sausage",
      "Jalapeños",
      "Red chili flakes",
      "Mozzarella",
    ],
    price: 13,
    image: "/images/spicy-inferno.jpg",
  },
  {
    id: 7,
    name: "Forest Feast",
    base: "cream",
    ingredients: [
      "Wild mushrooms",
      "Caramelized onions",
      "Truffle oil",
      "Parsley",
    ],
    price: 15,
    image: "/images/forest-feast.jpeg",
  },
  {
    id: 8,
    name: "Tropical Twist",
    base: "tomato",
    ingredients: ["Pineapple", "Ham", "Bacon", "Mozzarella"],
    price: 11,
    image: "/images/tropical-twist.jpg",
  },
  {
    id: 9,
    name: "Vegan Green",
    base: "tomato",
    ingredients: [
      "Zucchini",
      "Bell peppers",
      "Cherry tomatoes",
      "Vegan cheese",
    ],
    price: 12,
    image: "/images/vegan-green.jpg",
  },
  {
    id: 10,
    name: "BBQ Bliss",
    base: "tomato",
    ingredients: ["Pulled pork", "Red onions", "Corn", "Cheddar"],
    price: 16,
    image: "/images/bbq-grill.jpg",
  },
];
